export const SAVE_CAR_REQUEST = "SAVE_CAR_REQUEST";
export const FETCH_CAR_REQUEST = "FETCH_CAR_REQUEST";
export const UPDATE_CAR_REQUEST = "UPDATE_CAR_REQUEST";
export const DELETE_CAR_REQUEST = "DELETE_CAR_REQUEST";
export const CAR_SUCCESS = "CAR_SUCCESS";
export const CAR_FAILURE = "CAR_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
